function Event(type, data){
	this.type = type; // String name
	this.data = data; // wahtevs
}

Event.prototype.type = null;
Event.prototype.data = null;
Event.prototype.stopPropagation = false;
Event.prototype.target = null;
	
Event.ALL_REELS_SPINNING = "ALL_REELS_SPINNING";
Event.ALL_REELS_STOPPED = "ALL_REELS_STOPPED";
Event.ASSETS_LOADED = "ASSETS_LOADED";
Event.BET = "BET";
Event.BONUS_START = "BONUS_START";
Event.BONUS_COMPLETE = "BONUS_COMPLETE";
Event.GAME_COMPLETE = "GAME_COMPLETE";
Event.INVALID_RESPONSE_RECEIVED = "INVALID_RESPONSE_RECEIVED";
Event.REEL_SPINNING = "REEL_SPINNING";
Event.REEL_STOPPED = "REEL_STOPPED";
Event.RESIZE = "RESIZE";
Event.SPIN = "SPIN";
Event.STOP = "STOP";
Event.SYMBOL_ANIMATION_COMPLETE = "SYMBOL_ANIMATION_COMPLETE"; 
Event.VALID_RESPONSE_RECEIVED = "VALID_RESPONSE_RECEIVED";
Event.WIN_ANIMATOR_COMPLETE = "WIN_ANIMATOR_COMPLETE";
Event.WIN_DISPLAY_COMPLETE = "WIN_DISPLAY_COMPLETE"; 
Event.WIN_LINES_COMPLETE = "WIN_LINES_COMPLETE";
Event.WIN_SPLASH_COMPLETE = "WIN_SPLASH_COMPLETE";
Event.WIN_SUMMARY_COMPLETE = "WIN_SUMMARY_COMPLETE";
